### ISSUE TITLE
[Bug] Media control keys don't work in bluetooth mode

### ISSUE THREAD

**Issue by jmarmstrong1207** [OpenAnnePro/qmk_firmware#23]
The media keys work on wired mode but not on Bluetooth. Oddly enough, when switching back to wired mode, it still doesn't work. I need to plug out the cable to remove the power for it to work again.

## System Information

 - Keyboard:  anne pro 2
   - Revision (if applicable):  c18
 - Operating system: WIN 10
 - AVR GCC version: Not available. Not installed

 - ARM GCC version: arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

 - QMK Firmware version: Doesn't work. No names found. This is the master version as of the time this was posted.

**Comment by Codetector1374** [comment]
This is a "won't fix" since we are currently simply delivering the HID code to the bluetooth controller. Unless we can see how is the stock firmware is doing it, or is it supported at all? we can't really fix this

**Comment by Codetector1374** [comment]
If this works on stock firmware, and someone can do a UART capture of the communication between main MCU and BLE then we can implement this.

**Comment by thomazmoura** [comment]
I'm pretty sure it's supported because it works on native firmware and quite well, actually (I believe it's the only part that's currently better on the native firmware rather than the QMK version). But yeah, it might be useful to keep it as "help wanted" until someone who can help with this kind of capture comes along.

**Comment by Codetector1374** [comment]
yeah if someone can do the capture it’s not hard to implement it
