### ISSUE TITLE
[Feature Request] Add a release section for a compiled version

### ISSUE THREAD

**Issue by jmarmstrong1207** [OpenAnnePro/qmk_firmware#24]
It'll be easier for less tech-savvy users and for people who want to save time. Additionally, this could make the "how to install" section in the website essentially easier to navigate if we mention the compiled binaries.

**Comment by MycroftHolmes1989** [comment]
I would consider keeping the compiled bins out of the repo. They can be shared on Discord server or add a download link to OpenAnnePro site.

**Comment by Codetector1374** [comment]
The point of QMK is to be able to customize so have it precompiled sort of lose the point. We provide pre compiled shine since I expect quite some people to never modify shine
