### ISSUE TITLE
[Bug] Caps lock LED bugs out when used with an animated profile

### ISSUE THREAD

**Issue by jmarmstrong1207** [OpenAnnePro/qmk_firmware#25]
As what the title says. The LEDs freeze in many different ways. It usually freezes as one row of red, or none at all. The workaround is to turn off, then turn on the LEDs.

## System Information

 - Keyboard:  anne pro 2
   - Revision (if applicable):  c18
 - Operating system: WIN 10
 - AVR GCC version: Not available. Not installed

 - ARM GCC version: arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

 - QMK Firmware version: Doesn't work. No names found. This is the master version as of the time this was posted.

**Comment by thomazmoura** [comment]
The problem seems to be related to Shine, not QMK. I've made a PR to fix that on there:

https://github.com/OpenAnnePro/AnnePro2-Shine/pull/32

If you can take this issue there we can track it with this PR.

**Comment by jmarmstrong1207** [comment]
Alright, I'll close this page
