### ISSUE TITLE
Merging upstream back into this repository?

### ISSUE THREAD

**Issue by gmemstr** [OpenAnnePro/qmk_firmware#32]
Would it be worth merging in the work from upstream back into this repository? More than happy to put in the legwork (if any) to make this happen - I recognize a lot of the work upstream is around specific keyboard support and probably not the core firmware, but there are probably some things we can benefit from by merging.

**Comment by BachoSeven** [comment]
[this](https://github.com/OpenAnnePro/qmk_firmware/pull/34#issuecomment-782908997) comment didn't automatically close the issue because it only works from the PR title or commit message, however I guess it can be closed(?)
